# baseai/ruff.toml

# Ruff'un temel ayarları (Eskiden [tool.ruff] altındaydı)
target-version = "py311"
line-length = 100
respect-gitignore = true

# Linter ayarları (Eskiden [tool.ruff.lint] altındaydı)
[lint]
select = ["E","F","W","C90","I","UP","B","Q"]
ignore = ["E203","E501"]
fixable = ["ALL"]
unfixable = ["F401","F841"] # kritik: import/unused değişkenleri ruff silmesin

# ISort ayarları (Eskiden [tool.ruff.lint.isort] altındaydı)
[lint.isort]
known-first-party = ["baseai"]

# Formatlayıcı ayarları (Eskiden [tool.ruff.format] altındaydı)
[format]
quote-style = "preserve"