"""
BaseAI - BinAI v20.3 Mimarisi
Ana Konfigürasyon Dosyası (Restorasyonu)
(v19.0 "Derin Evrim" + v16.0 "Fırsatçı Yeniden Dengeleme" içerir)
"""

# === ÇEKİRDEK API AYARLARI ===
API_KEY = "YOUR_PRODUCTION_API_KEY"
API_SECRET = "YOUR_PRODUCTION_API_SECRET"
TESTNET_API_KEY = "j6u7LwkGO03XY7FD2BNoEeMrdj80xGxlVZdssLMEjvCfHt9ORd5HkHGTMxASPXPA"
TESTNET_API_SECRET = "jxW9lyD9ppwIvVo8gd9LnUCP1R1H6YZAgZGrs9JXAlVGXakmoVTiftrcWsHbqDm0"
USE_TESTNET = True

# === PİYASA TARAMA MİMARİSİ ===
MARKET_SCAN_ENABLED = True
SYMBOLS_BLACKLIST = ["USDCUSDT", "BUSDUSDT", "TUSDUSDT", "FDUSDUSDT"]
MIN_24H_VOLUME_USDT = 50000000
SYMBOLS_WHITELIST = ["BTCUSDT", "ETHUSDT"] # Backtester v9.0 tarafından kullanılır

# === v15.0 "SONSUZ OTONOMİ" DÖNGÜSÜ ===
OPTIMIZATION_INTERVAL_HOURS = 12 # 12 saatte bir

# === v19.0 "DERİN EVRİM" (Deep Evolution) VERİ DERİNLİĞİ ===
DEEP_EVOLUTION_KLINE_LIMIT = 15000 # (50+ gün)
BACKTEST_KLINE_LIMIT = 1500 # (5 gün)

# === v16.0 "FIRSATÇI YENİDEN DENGELEME" (Opportunistic Rebalancing) ===
OPPORTUNISTIC_REBALANCE_ENABLED = True
OPPORTUNISTIC_REBALANCE_THRESHOLD = 0.95 # (Güven Puanı %95'in üzerinde olmalı)

# === STRATEJİ MİMARİSİ (v11.0 - PİYASA REJİMİ TESPİTİ) ===
INTERVAL = "5m" 
MIN_SIGNAL_CONFIDENCE = 0.80
ADX_PERIOD = 14
ADX_TREND_THRESHOLD = 25 

# === v10.3 "Trend Takip" Stratejisi Parametreleri (Evrim Motoru tarafından optimize edildi) ===
FAST_MA_PERIOD = 20
SLOW_MA_PERIOD = 50
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
VOLUME_AVG_PERIOD = 20

# === v11.0 "Yatay Piyasa" (Ranging) Stratejisi Parametreleri ===
RANGING_RSI_PERIOD = 14
RANGING_RSI_OVERSOLD = 30
RANGING_RSI_OVERBOUGHT = 70

# === KASA DOKTRİNİ (v5.3) ===
MAX_CONCURRENT_POSITIONS = 2
LEVERAGE = 10
POSITION_SIZE_PERCENT = 0.50

# === KAR/ZARAR HEDEFLERİ (v6.1 - Öğrenilmiş Parametreler) ===
STOP_LOSS_PERCENT = 0.015
TAKE_PROFIT_PERCENT = 0.03

# === v13.0 KORELASYONLU RİSK YÖNETİMİ ===
CORRELATION_CHECK_ENABLED = True
CORRELATION_THRESHOLD = 0.80
CORRELATION_KLINE_LIMIT = 500

# === LOGLAMA AYARLARI ===
LOG_LEVEL = "INFO"
LOG_FILE = "binai_runtime.log"