"""
BaseAI - BinAI v22.0 Mimarisi
Ana Konfigürasyon Dosyası (Enterprise Core)

v22.0 Yükseltmeleri:
- Analiz Yeteneği Güçlendirildi: MACD ve Bollinger Bantları parametreleri eklendi.
- 'SMA' yerine 'EMA' kullanımı için varsayılanlar güncellendi.
"""

# === ÇEKİRDEK API AYARLARI ===
API_KEY = "YOUR_PRODUCTION_API_KEY"
API_SECRET = "YOUR_PRODUCTION_API_SECRET"
TESTNET_API_KEY = "j6u7LwkGO03XY7FD2BNoEeMrdj80xGxlVZdssLMEjvCfHt9ORd5HkHGTMxASPXPA"
TESTNET_API_SECRET = "jxW9lyD9ppwIvVo8gd9LnUCP1R1H6YZAgZGrs9JXAlVGXakmoVTiftrcWsHbqDm0"
USE_TESTNET = True

# === PİYASA TARAMA MİMARİSİ ===
MARKET_SCAN_ENABLED = True
SYMBOLS_BLACKLIST = ["USDCUSDT", "BUSDUSDT", "TUSDUSDT", "FDUSDUSDT", "USDTTRY"]
MIN_24H_VOLUME_USDT = 50000000
SYMBOLS_WHITELIST = ["BTCUSDT", "ETHUSDT"]

# === v20.0 WEBSOCKET MOTORU ===
MIN_CACHE_SYMBOLS = 100 

# === v21.0 ÇEKİRDEK MOTOR AYARLARI ===
MAIN_LOOP_SLEEP_SECONDS = 5 
CRITICAL_ERROR_SLEEP_SECONDS = 30 

# === v21.3 REAKTİF OTONOMİ ===
REACTIVE_ANALYSIS_INTERVAL_MINUTES = 60 

# === v19.0 DERİN EVRİM ===
DEEP_EVOLUTION_KLINE_LIMIT = 15000 
BACKTEST_KLINE_LIMIT = 1500 

# === v16.0 FIRSATÇI YENİDEN DENGELEME (GÜVENLİ MOD: KAPALI) ===
OPPORTUNISTIC_REBALANCE_ENABLED = True 
OPPORTUNISTIC_REBALANCE_THRESHOLD = 0.95 

# === STRATEJİ MİMARİSİ ===
INTERVAL = "5m" 
MIN_SIGNAL_CONFIDENCE = 0.90 # (Yüksek Güven)
ADX_PERIOD = 14
ADX_TREND_THRESHOLD = 25 
MIN_KLINES_FOR_STRATEGY = 200 

# === v22.0 TREND STRATEJİSİ (EMA + MACD + RSI) ===
# Hareketli Ortalamalar (EMA)
EMA_FAST_PERIOD = 9   # (Daha hızlı tepki için 20'den 9'a düşürüldü)
EMA_SLOW_PERIOD = 21  # (50'den 21'e düşürüldü - Scalping için)
# MACD (Momentum)
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
# RSI Filtresi
RSI_PERIOD = 14
RSI_OVERSOLD = 40 # (Trend yönünde düzeltme yakalamak için)
RSI_OVERBOUGHT = 60 
VOLUME_AVG_PERIOD = 20

# === v22.0 YATAY STRATEJİSİ (BOLLINGER + RSI) ===
BB_LENGTH = 20
BB_STD = 2.0 # Standart Sapma (2.0 standarttır, 2.5 daha az ama öz işlem açar)
RANGING_RSI_PERIOD = 14
RANGING_RSI_OVERSOLD = 30
RANGING_RSI_OVERBOUGHT = 70

# === KASA DOKTRİNİ (v21.5 ISOLATED) ===
MAX_CONCURRENT_POSITIONS = 3
LEVERAGE = 10
MARGIN_TYPE = "ISOLATED"

# --- SÜPER ÖZELLİK #2: DİNAMİK POZİSYON BOYUTU ---
USE_DYNAMIC_POSITION_SIZING = True
RISK_PER_TRADE_PERCENT = 0.02 
POSITION_SIZE_PERCENT = 0.50 

# === KAR/ZARAR HEDEFLERİ ===
STOP_LOSS_PERCENT = 0.03
TAKE_PROFIT_PERCENT = 0.06 # (Risk/Ödül 1:2 hedeflendi)

# === SÜPER ÖZELLİK #1: DİNAMİK SL/TP ===
USE_DYNAMIC_SLTP = True
ATR_STOP_LOSS_MULTIPLIER = 3.0
ATR_TAKE_PROFIT_MULTIPLIER = 6.0

# === v13.0 KORELASYONLU RİSK YÖNETİMİ ===
CORRELATION_CHECK_ENABLED = True
CORRELATION_THRESHOLD = 0.80
CORRELATION_KLINE_LIMIT = 500

# === LOGLAMA AYARLARI ===
LOG_LEVEL = "INFO"
CORE_LOG_FILE = "binai_runtime.log"